# Site settings
title: "Laith Azer - Toronto Ruby on Rails & ReactJS developer"
author: "Laith Azer"
keywords: "toronto, web developer, ruby, ruby on rails, actioncable, javascript, reactjs, redux, senior developer, mentor"
biography: "I am a Toronto based full-stack developer who works with Ruby on Rails and React/Redux. Currently Technical Lead at Think Research."
description: "I am a Toronto based full-stack developer who works with Ruby on Rails and React/Redux. Currently Technical Lead at Think Research."
colophon: ""

baseurl: ""
url: ""

github_username: laithazer
linkedin_username: laithazer
email: laith.azer@gmail.com

markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
